#pragma config(Sensor, dgtl1,  ir1,            sensorDigitalIn)
#pragma config(Sensor, dgtl2,  ir2,            sensorDigitalIn)
#pragma config(Motor,  port2,           motorR,        tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port3,           motorL,        tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port4,           motorU,        tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port5,           servo1,        tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port6,           servo2,        tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port10,          fl,            tmotorVexFlashlight, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main(){
	//floats
	float multiplier = 1.0;
	float deadzoneA = 0.0;
	float deadzoneB = 0.0;
  	//integers
	int rightcounter = 0;
  	int leftcounter = 0;
  	//booleans
	bool rightcounterdebounce = false;
 	bool leftcounterdebounce = false;
 	bool pushed = false;
  	//general loop for detection on the robot
	while (true){
		//left and right wheels
		if(vexRT[Ch3] > 27 || vexRT[Ch3] < -27){
			deadzoneA = vexRT[Ch3];
		}else{
			deadzoneA = 0;
		}

		if(vexRT[Ch2] > 27 || vexRT[Ch2] < -27){
			deadzoneB = vexRT[Ch2];
		}else{
			deadzoneB = 0;
		}

		motor[motorR] = -deadzoneB/multiplier;
		motor[motorL] = deadzoneA/multiplier;
		
		//pulley motor forwards
		if(vexRT[Btn5U] == 1){
			startMotor(port4,127);
			delay(1);
			stopMotor(port4);
		}
		//pulley motor backwards
		else if(vexRT[Btn5D] == 1){
			startMotor(port4,-127);
			delay(1);
			stopMotor(port4);
		}

		//claw motor
		if(vexRT[Btn6U] == 1){
			startMotor(servo1,127);
			delay(1);
			stopMotor(servo1);
		}
		//claw backwards
		else if(vexRT[Btn6D] == 1){
			startMotor(servo1,-127);
			delay(1);
			stopMotor(servo1);
		}

		//light pole mag motor
		if(vexRT[Btn7U] == 1){
			startMotor(port6,127);
			delay(1);
			stopMotor(port6);
		}
		//light pole mag backwards
		else if(vexRT[Btn8U] == 1){
			startMotor(port6,-127);
			delay(1);
			stopMotor(port6);
		}

		//both pushed do nothing
		if (vexRT[Btn7L] == 1 && vexRT[Btn8R] == 1) {
			pushed = true;
		}
		//half speed
		else if(vexRT[Btn7L] == 1 && !pushed && multiplier == 2.0){
			pushed = true;
			multiplier = 1.0;
		}
		else if(vexRT[Btn7L] == 1 && !pushed){
			pushed = true;
			multiplier = 2.0;
		}
		//quarter speed
		else if(vexRT[Btn8R] == 1 && !pushed && multiplier == 4.0){
			pushed = true;
			multiplier = 1.0;
		}
		else if(vexRT[Btn8R] == 1 && !pushed){
			pushed = true;
			multiplier = 4.0;
		}
		//none pushed do nothing
		else if (vexRT[Btn7L] == 0 && vexRT[Btn8R] == 0) {
			pushed = false;
		}
		//resets speed
		if(vexRT[Btn7D] == 1 || vexRT[Btn8D] == 1){
			multiplier = 1.0;
		}

		if(vexRT[Btn8L] == 1){
			rightcounter = 0;
			leftcounter = 0;
			rightcounterdebounce = false;
			leftcounterdebounce = false;
		}
		//Auton (IR)
		else if (vexRT[Btn7R] == 1) {
			startMotor(motorL, 127);
			startMotor(motorR, -127);
			delay(0.4);
			stopMotor(motorL);
			stopMotor(motorR);
			delay(0.4);
			motor[servo1] = 127;
			delay(0.4);
			startMotor(motorL, -127);
 			startMotor(motorR, 127);
 			delay(0.4);
			stopMotor(motorL);
			stopMotor(motorR);
		}
	}
}